import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "BMI Calculator";
    width: 400px;
    height: 350px; 

    callback calculate-bmi();

    in-out property <string> weight-text: "";
    in-out property <string> height-text: "";
    in-out property <string> result-text: "";

    VerticalBox {
        alignment: center;
        spacing: 15px;

        Text {
            text: "Weight (kg):";
            horizontal-alignment: center;
        }

        LineEdit {
            text <=> root.weight-text;
            placeholder-text: "for example: 70";
            max-width: 200px;
        }

        Text {
            text: "Height (cm):";
            horizontal-alignment: center;
        }

        LineEdit {
            text <=> root.height-text;
            placeholder-text: "for example: 165";
            max-width: 200px;
        }


        Button {
            text: "Calculate Your BMI index";
            max-width: 200px;
            clicked => { root.calculate-bmi(); }
        }

        Text {
            text: root.result-text;
            horizontal-alignment: center;
            font-size: 16px; 
        }
    }
}

